### ISSUE TITLE
"External Subtitles" for Samsung and LG TVs

### ISSUE THREAD

**Issue by leonelsr** [oeuillot/upnpserver#12]
Where would I start to look in the code if I wanted to add support for external subtitles (that's not on the specs but LG and Samsung TVs support)?

I already now that it is ["as simple as"](https://github.com/haku/dlnatoad/issues/1) adding a `<res />` with the path to the SRT file.

**Comment by oeuillot** [comment]
Can you test the 1.4.0 version ?
