### ISSUE TITLE
refactor question

### ISSUE THREAD

**Issue by Karnith** [oeuillot/upnpserver#20]
I've been looking through the code and wondered if renderer profiles should be moved to xml or json files. This could add flexibility to integrate ffmpeg with the dlna service for real time transcoding, which would then allow media encoded in an unsupported format to play on the renderer.  See http://serviio.org/index.php?option=com_content&view=article&id=16 for an example.

Thoughts?

**Comment by oeuillot** [comment]
Hello,
Why not ... 
But currently, I prefer develop extensions entries, to invite other developers/sub-projects to develop some particular points.

**Comment by Karnith** [comment]
Old post
