### ISSUE TITLE
Does not work on windows 8.1.

### ISSUE THREAD

**Issue by puttyman** [oeuillot/upnpserver#26]
I have tried to get it to work on windows 8.1 with no success. However works fine on my Ubuntu 14 VM. Any help would be appreciated. Thank you :)

**Comment by oeuillot** [comment]
Hello puttyman,
I develop upnpserver with Eclipse on a Windows 8.1 !!!!
Which version of nodejs do you use ?
Can you post me a console log ?
Regards,

**Comment by puttyman** [comment]
Ok it doesn't work with node v0.12. Switched to v0.10 works flawlessly. I saw there is another ticket in regards to node 0.12 and a fix has been made. Is it because the version on npm isn't the latest?

**Comment by oeuillot** [comment]
see https://github.com/diversario/node-ssdp/issues/28

I have committed some fixes for node v0.12.
I use node-ssdp 2.0.1 and it works fine for me (Windows 8.1 - 64bits - nodejs 0.12)

**Comment by puttyman** [comment]
Thanks @oeuillot .
