### ISSUE TITLE
file parsing fail

### ISSUE THREAD

**Issue by smolleyes** [oeuillot/upnpserver#27]
hello olivier

updated upnserver yesterday and have some problems for files listing

on my video folder it won t show any file, errors:
```
"Can not find target for offset=4099 doc=[Document source=[Source file=/media/partage/videos/films/[ something ] truc.mkv]]"", source: /media/partage/projets/streamstudio/src/node_modules/upnpserver/node_modules/matroska/lib/document.js (192)
```
(i removed the filename)

and audio files
```
""MM can not parse tags of path=" "/media/partage/saves/Musique/Wu-Tang Clan - 2014 - A Better Tomorrow/Wu-Tang Clan - A Better Tomorrow.m3u" " error="", source: /media/partage/projets/streamstudio/src/node_modules/upnpserver/lib/contentHandlers/audio_musicmetadata.js (49)
```
on another pc it won t load any files at all...

```
/home/yasmin/Documents/StreamStudio/node_modules/upnpserver/lib/contentDirectoryService.js:501 Uncaught TypeError: undefined is not a function
```

thanks :)

**Comment by oeuillot** [comment]
Hello smolleyes

I forgot to package node-matroska. I am publishing the 2.2.2 version.

So please, get the last version of upnpserver 2.1.3  and don't forget to do
a "npm update".

I hope, it will fix your problems.  (Your 2 messages are only some logs,
nothing severe !)

Regards,

Olivier


2015-06-23 9:34 GMT+02:00 smolleyes <notifications@github.com>:

**Comment by smolleyes** [comment]
ok

works right :+1: 

small idear

develop a upnp renderer for android thru jxcore (tested it works well)

just a service where we can send video/audio with a complete player or just starting an external player

all apps tested for this do not works well or at all :/

think you can make lot of moneyt with this (freebox 4k for exemple)

try airpin for exemple but it ask a player each time we start a file...

**Comment by oeuillot** [comment]
Hello ... I am currently testing the new freebox player QML API !!!!
There are lot's of thing to do  :-)

**Comment by oeuillot** [comment]
Done
