### ISSUE TITLE
Test are not running on Yosemite

### ISSUE THREAD

**Issue by fcduarte** [oeuillot/upnpserver#28]
Hi,

I'm trying to test the library and I'm getting this error after a `make test`:

```
[Error: Module did not self-register.]
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }


  API
    1) Path as string should be valid
    2) Path as object should be valid
    3) Should add directory
    4) Should add music directory


  0 passing (104ms)
  4 failing
...
```

Does it work on a Mac? I also tried to start a server but it's not working either. I started upnpserver-cli but I wasn't able to see my files on both VLC (Under "Local Network" -> "Universal Plug'n'Play" ) and PS4 Media player .. Any insight appreciated, thanks!

**Comment by oeuillot** [comment]
Hello 
Test units are not terminated, forget them :-( 

I have never tested it on a Mac ...

Can you put upnpserver logs in this thread ?

You can enable logging by setting in your ENV:
export DEBUG=upnpserver,upnpserver:contentDirectoryService,upnpserver:contentDirectoryService:*

and launch upnpserver-cli !

Regards,

**Comment by fcduarte** [comment]
Hi,

so here is my `server.js`:

````
var Server = require("../");

var server = new Server({ dlnaSupport: true }, [
  { path: '/Users/<my-username>/Movies', mountPoint: '/', type: 'video' }

]);

server.start();
````

After running it here's the log:

````
 upnpserver:contentDirectoryService Handler Mime 'audio/*' => [UpnpClass object.item.audioItem.musicTrack] +0ms
  upnpserver:contentDirectoryService Handler Mime 'video/*' => [UpnpClass object.item.videoItem],[UpnpClass object.item.videoItem.movie],[UpnpClass object.item.videoItem.musicVideoClip],[UpnpClass object.item.videoItem.videoBroadcast] +2ms
  upnpserver:contentDirectoryService Handler Mime 'image/*' => [UpnpClass object.item.imageItem] +2ms
  upnpserver:contentDirectoryService Handler Mime 'image/jpeg' => [UpnpClass object.item.imageItem.photo] +0ms
  upnpserver:contentDirectoryService Adding  +2ms 1  repositories
  upnpserver:contentDirectoryService Adding repository +1ms /
Ready http://[::]:10293
````

If you have some time please take a look here -- https://www.diffchecker.com/s7jscdu3  -- this is the difference of XML Device Description between Serviio (which is working under VLC) and upnpserver .. Also another difference is that Serviio serves the XML description at `http://<local-ip>:8895/deviceDescription/<generated-uuid>` and upnpserver at `http://<local-ip>:10293/DeviceDescrition.xml`

Any ideas?

**Comment by oeuillot** [comment]
Hello,
Which version of VLC you use ? the latest ?   (VLC is the worst of all upnp clients I have tested, but I use it everyday !!!)
Have you more logs (after the "Ready http://")  ?

I am more interested by the PS4:  is it a simple upnp client, or a DLNA client ? Have you more logs ?
What happens ?

Regards

**Comment by fcduarte** [comment]
Hi,

I'm using latest VLC .. I just mentioned it because both PS4 and VLC are able to find Serviio's media. Anyway I'm also more interested on the PS4 :)

About logs, the answer is no, I get nothing after "Ready.." .. What should I be seeing there?

On the PS4 there's an app called Media Player: http://blog.us.playstation.com/2015/06/15/media-player-coming-to-ps4/ -- I'm not sure about the difference between a upnp client and a DLNA client .. On its main screen it can see Serviio and I can select any media to play.

Let me know if I can help with more information.

Best,

**Comment by rfigueroa** [comment]
I think ps4 media player is a DLNA app

**Comment by oeuillot** [comment]
I try to support DLNA, but there are a lot of hard coded values I don't known, I can't test !
If someone would propose some "magic values", he is welcome !
