### ISSUE TITLE
Update Example

### ISSUE THREAD

**Issue by gak10100** [oeuillot/upnpserver#49]
In the example configuration it says

dlnaSupport Boolean Enable/disable dlna support. Default: true

However on line 46 of upnpServer.js it has

this.dlnaSupport = !!configuration.dlna;

The example should say
dlna Boolean Enable/disable dlna support. Default: false

**Comment by oeuillot** [comment]
Hello,
I rewrite the configuration in branch ES6.
Please , switch to this branch, or wait the merge ;-)

In the new branch, I have set the default value of dlna support to TRUE.

Regards,
