### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ajmas** [oeuillot/upnpserver#60]
Are there any plans to make a new release, since the 2.1.3 version is already fairly, based on current HEAD state?

**Comment by oeuillot** [comment]
Soon, 
Have you tested the Head ?
I use the HEAD version for 4 months, and I have not detected any problems !

Regards,

**Comment by ajmas** [comment]
I have briefly. I was able to access the contents using VLC on my Apple TV.

BTW is there any mechanism to plug in a database, such as mongo, to retain state? I am looking to use it your solution on a Raspberry Pi, for use an in-car server.

**Comment by roccomuso** [comment]
+1

**Comment by oeuillot** [comment]
Hello, can you try the new release ?
