### ISSUE TITLE
add headers for smamsung tv

### ISSUE THREAD

**Issue by smolleyes** [oeuillot/upnpserver#7]
hello olivier :)

i m working on upnp client for my app, i know have mediarendering working if servers have

response.setHeader('transferMode.dlna.org', 'Streaming')
 response.setHeader('contentFeatures.dlna.org','DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=017000 00000000000000000000000000');

in the code

add it to your upnpServer.js  after line 193 and everything works fine, works in xmbc/freebox and my samsung tv now :dancer: 

ht5streamer is now fiull upnpserver/client :p just need to work on events subscribe now !

++

**Comment by oeuillot** [comment]
Issue closed
